# Site settings
title: Clinica Psi Cedofeita
description: Clínica de Psiquiatria e Psicologia localizada na Rua de Cedofeita, no Porto.
keywords: médico, psiquiatria, psicologia, psiquiatra, psicólogo, cedofeita, porto, clínica, consultório, ajuda, exames, cabeça, pecegueiro, aguilar
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# ">" : this means to ignore newlines until the next tag
