# Site settings
title: Clinica Psi Cedofeita
description: Clínica de Psiquiatria e Psicologia localizada na Rua de Cedofeita, no Porto.
keywords: psiquiatria, psicologia, psiquiatra, psicólogo, cedofeita, clínica, consultórios, ajuda, exames, cabeça
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# ">" : this means to ignore newlines until the next tag
